
import CalcoloEspressione.Espressione;

public class Calcolatrice extends javax.swing.JFrame {

	Espressione e;
	
	/**
	 * Creates new form Calcolatrice
	 */
	public Calcolatrice() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sette = new javax.swing.JButton();
        otto = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        quattro = new javax.swing.JButton();
        cinque = new javax.swing.JButton();
        sei = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        due = new javax.swing.JButton();
        tre = new javax.swing.JButton();
        virgola = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        uguale = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        del = new javax.swing.JButton();
        potenza = new javax.swing.JButton();
        sottrazione = new javax.swing.JButton();
        addizione = new javax.swing.JButton();
        divisione = new javax.swing.JButton();
        moltiplicazione = new javax.swing.JButton();
        apertaParentesi = new javax.swing.JButton();
        chiusaParentesi = new javax.swing.JButton();
        testo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        canc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        sette.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        sette.setText("7");
        sette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setteActionPerformed(evt);
            }
        });
        jPanel1.add(sette);

        otto.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        otto.setText("8");
        otto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottoActionPerformed(evt);
            }
        });
        jPanel1.add(otto);

        nove.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });
        jPanel1.add(nove);

        quattro.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        quattro.setText("4");
        quattro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quattroActionPerformed(evt);
            }
        });
        jPanel1.add(quattro);

        cinque.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cinque.setText("5");
        cinque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinqueActionPerformed(evt);
            }
        });
        jPanel1.add(cinque);

        sei.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        sei.setText("6");
        sei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seiActionPerformed(evt);
            }
        });
        jPanel1.add(sei);

        uno.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        uno.setText("1");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel1.add(uno);

        due.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        due.setText("2");
        due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueActionPerformed(evt);
            }
        });
        jPanel1.add(due);

        tre.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        tre.setText("3");
        tre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treActionPerformed(evt);
            }
        });
        jPanel1.add(tre);

        virgola.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        virgola.setText(".");
        virgola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virgolaActionPerformed(evt);
            }
        });
        jPanel1.add(virgola);

        zero.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel1.add(zero);

        uguale.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        uguale.setText("=");
        uguale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugualeActionPerformed(evt);
            }
        });
        jPanel1.add(uguale);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        del.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        del.setText("DEL");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel2.add(del);

        potenza.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        potenza.setText("^");
        potenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenzaActionPerformed(evt);
            }
        });
        jPanel2.add(potenza);

        sottrazione.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        sottrazione.setText("-");
        sottrazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sottrazioneActionPerformed(evt);
            }
        });
        jPanel2.add(sottrazione);

        addizione.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addizione.setText("+");
        addizione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addizioneActionPerformed(evt);
            }
        });
        jPanel2.add(addizione);

        divisione.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        divisione.setText("÷");
        divisione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisioneActionPerformed(evt);
            }
        });
        jPanel2.add(divisione);

        moltiplicazione.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        moltiplicazione.setText("×");
        moltiplicazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moltiplicazioneActionPerformed(evt);
            }
        });
        jPanel2.add(moltiplicazione);

        apertaParentesi.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        apertaParentesi.setText("(");
        apertaParentesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apertaParentesiActionPerformed(evt);
            }
        });
        jPanel2.add(apertaParentesi);

        chiusaParentesi.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        chiusaParentesi.setText(")");
        chiusaParentesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiusaParentesiActionPerformed(evt);
            }
        });
        jPanel2.add(chiusaParentesi);

        jPanel3.setLayout(new java.awt.GridLayout());

        canc.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        canc.setText("C");
        canc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancActionPerformed(evt);
            }
        });
        jPanel3.add(canc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(testo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testo)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        add('0');
    }//GEN-LAST:event_zeroActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        add('1');
    }//GEN-LAST:event_unoActionPerformed

    private void dueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueActionPerformed
        add('2');
    }//GEN-LAST:event_dueActionPerformed

    private void treActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treActionPerformed
        add('3');
    }//GEN-LAST:event_treActionPerformed

    private void quattroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quattroActionPerformed
        add('4');
    }//GEN-LAST:event_quattroActionPerformed

    private void cinqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinqueActionPerformed
        add('5');
    }//GEN-LAST:event_cinqueActionPerformed

    private void seiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seiActionPerformed
        add('6');
    }//GEN-LAST:event_seiActionPerformed

    private void setteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setteActionPerformed
        add('7');
    }//GEN-LAST:event_setteActionPerformed

    private void ottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottoActionPerformed
        add('8');
    }//GEN-LAST:event_ottoActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        add('9');
    }//GEN-LAST:event_noveActionPerformed

    private void ugualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugualeActionPerformed
		e = new Espressione(testo.getText());
        System.out.println(e.getRis());
        testo.setText(e.getRis() + "");
    }//GEN-LAST:event_ugualeActionPerformed

    private void virgolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virgolaActionPerformed
        add(',');
    }//GEN-LAST:event_virgolaActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
		if (testo.getText().length() > 0) {
			int i=testo.getText().length();
            testo.setText(testo.getText().substring(0, i-1));
        }
    }//GEN-LAST:event_delActionPerformed

    private void divisioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisioneActionPerformed
		add('/');
    }//GEN-LAST:event_divisioneActionPerformed

    private void moltiplicazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moltiplicazioneActionPerformed
        add('*');
    }//GEN-LAST:event_moltiplicazioneActionPerformed

    private void sottrazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sottrazioneActionPerformed
        add('-');
    }//GEN-LAST:event_sottrazioneActionPerformed

    private void addizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addizioneActionPerformed
        add('+');
    }//GEN-LAST:event_addizioneActionPerformed

    private void potenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenzaActionPerformed
        add('^');
    }//GEN-LAST:event_potenzaActionPerformed

    private void apertaParentesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apertaParentesiActionPerformed
        add('(');
    }//GEN-LAST:event_apertaParentesiActionPerformed

    private void chiusaParentesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiusaParentesiActionPerformed
        add(')');
    }//GEN-LAST:event_chiusaParentesiActionPerformed

    private void cancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancActionPerformed
        testo.setText("");
    }//GEN-LAST:event_cancActionPerformed

	private void add(char n){
		testo.setText(testo.getText() + "" + n);
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new Calcolatrice().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addizione;
    private javax.swing.JButton apertaParentesi;
    private javax.swing.JButton canc;
    private javax.swing.JButton chiusaParentesi;
    private javax.swing.JButton cinque;
    private javax.swing.JButton del;
    private javax.swing.JButton divisione;
    private javax.swing.JButton due;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton moltiplicazione;
    private javax.swing.JButton nove;
    private javax.swing.JButton otto;
    private javax.swing.JButton potenza;
    private javax.swing.JButton quattro;
    private javax.swing.JButton sei;
    private javax.swing.JButton sette;
    private javax.swing.JButton sottrazione;
    private javax.swing.JTextField testo;
    private javax.swing.JButton tre;
    private javax.swing.JButton uguale;
    private javax.swing.JButton uno;
    private javax.swing.JButton virgola;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
